language: bash

sudo: required
dist: trusty

cache:
  directories:
    - workspace

branches:
  only:
    - /^\d+.*$/


install:
  - sudo apt-get update && sudo apt-get install -y p7zip-full


jobs:
  include:
    - &download
      stage: departement download
      script: bash scripts/departement/download.sh $DEP
      env: DEP=075
    - <<: *download
      env: DEP=093
    - <<: *download
      env: DEP=094
    - <<: *download
      env: DEP=092
    - &prepare
      stage: departement prepare
      script: 
        - chmod -R 777 workspace
        - bash scripts/departement/prepare.sh $DEP
      env: DEP=075
    - <<: *prepare
      env: DEP=093
    - <<: *prepare
      env: DEP=094
    - <<: *prepare
      env: DEP=092
    - &generate
      stage: departement generate
      script: 
        - chmod -R 777 workspace
        - bash scripts/departement/generate.sh $DEP
      env: DEP=075
      deploy:
        provider: releases
        api_key: $GH_TOKEN
        file_glob: true
        file: workspace/**/*.tar.gz
        skip_cleanup: true
        on:
          repo: tcoupin/rok4_gen_bdortho
          tags: true
    - <<: *generate
      env: DEP=093
    - <<: *generate
      env: DEP=094
    - <<: *generate
      env: DEP=092
    - &docker
      stage: departement docker
      script: 
        - chmod -R 777 workspace
        - bash scripts/departement/docker-image.sh $DEP
      env: DEP=075
    - <<: *docker
      env: DEP=093
    - <<: *docker
      env: DEP=094
    - <<: *docker
      env: DEP=092
    - stage: world download
      script: bash scripts/world/download.sh $DEPS
      env: DEPS="75,93,94,92"
    - stage: world prepare
      script: 
        - chmod -R 777 workspace
        - bash scripts/world/prepare.sh $DEPS
      env: DEPS="75,93,94,92"
    - stage: world generate
      script: 
        - chmod -R 777 workspace
        - bash scripts/world/generate.sh
      env: DEPS="75,93,94,92"
      deploy:
        provider: releases
        api_key: $GH_TOKEN
        file_glob: true
        file: workspace/**/*.tar.gz
        skip_cleanup: true
        on:
          repo: tcoupin/rok4_gen_bdortho
          tags: true
    - stage: world docker
      script: 
        - chmod -R 777 workspace
        - bash scripts/world/docker-image.sh 
      env: DEPS="75,93,94,92"

