language: bash

sudo: required
dist: trusty

cache:
  directories:
    - workspace

branches:
  only:
    - /^\d+.*$/


install:
  - sudo apt-get update && sudo apt-get install -y p7zip-full


jobs:
  include:
    - &download
      stage: departement download
      script: bash scripts/.travis/batch.sh scripts/departement/download.sh 75,93,94,92
    - &prepare
      stage: departement prepare
      script: 
        - chmod -R 777 workspace
        - bash scripts/.travis/batch.sh scripts/departement/prepare.sh 75,93,94,92
    - &generate
      stage: departement generate
      script: 
        - chmod -R 777 workspace
        - bash scripts/.travis/split.sh 4 1 scripts/departement/generate.sh scripts/departement/docker-image.sh
      deploy:
        provider: releases
        api_key: $GH_TOKEN
        file_glob: true
        file: workspace/**/*.tar.gz
        skip_cleanup: true
        overwrite: true
        on:
          repo: tcoupin/rok4_gen_bdortho
          tags: true
    - <<: *generate
      script: 
        - chmod -R 777 workspace
        - bash scripts/.travis/split.sh 4 2 scripts/departement/generate.sh scripts/departement/docker-image.sh
    - <<: *generate
      script: 
        - chmod -R 777 workspace
        - bash scripts/.travis/split.sh 4 3 scripts/departement/generate.sh scripts/departement/docker-image.sh
    - <<: *generate
      script: 
        - chmod -R 777 workspace
        - bash scripts/.travis/split.sh 4 4 scripts/departement/generate.sh scripts/departement/docker-image.sh
    - stage: world download
      script: bash scripts/world/download.sh 75,93,94,92
    - stage: world prepare
      script: 
        - chmod -R 777 workspace
        - bash scripts/world/prepare.sh 75,93,94,92
    - stage: world generate
      script: 
        - chmod -R 777 workspace
        - bash scripts/world/generate.sh
      deploy:
        provider: releases
        api_key: $GH_TOKEN
        file_glob: true
        file: workspace/**/*.tar.gz
        skip_cleanup: true
        overwrite: true
        on:
          repo: tcoupin/rok4_gen_bdortho
          tags: true
    - stage: world docker
      script: 
        - chmod -R 777 workspace
        - bash scripts/world/docker-image.sh 

