language: bash

sudo: required
dist: trusty

cache:
  directories:
    - workspace

branches:
  only:
    - /^\d+.*$/


install:
  - sudo apt-get update && sudo apt-get install -y p7zip-full


jobs:
  include:
    - stage: departement download
      script: bash scripts/departement/download.sh 075
    - script: bash scripts/departement/download.sh 093
    - script: bash scripts/departement/download.sh 094
    - script: bash scripts/departement/download.sh 092
    - stage: departement prepare
      script: bash scripts/departement/prepare.sh 075
    - script: bash scripts/departement/prepare.sh 093
    - script: bash scripts/departement/prepare.sh 094
    - script: bash scripts/departement/prepare.sh 092
    - stage: departement archive
      script: bash scripts/departement/generate.sh 075
    - script: bash scripts/departement/generate.sh 093
    - script: bash scripts/departement/generate.sh 094
    - script: bash scripts/departement/generate.sh 092
    
#001
#002
#003
#004
#005
#006
#007
#008
#009
#010
#011
#012
#013
#014
#015
#016
#017
#018
#019
#021
#022
#023
#024
#025
#026
#027
#028
#029
#02A
#02B
#030
#031
#032
#033
#034
#035
#036
#037
#038
#039
#040
#041
#042
#043
#044
#045
#046
#047
#048
#049
#050
#051
#052
#053
#054
#055
#056
#057
#058
#059
#060
#061
#062
#063
#064
#065
#066
#067
#068
#069
#070
#071
#072
#073
#074
#075
#076
#077
#078
#079
#080
#081
#082
#083
#084
#085
#086
#087
#088
#089
#090
#091
#092
#093
#094
#095
#971
#972
#973
#974
#975
#976
#977
#978
#986


deploy:
  provider: releases
  api_key: $GH_TOKEN
  file_glob: true
  file: workspace/**/D*.tar.gz
  skip_cleanup: true
  on:
    repo: tcoupin/rok4_gen_bdortho
    tags: true