language: bash

sudo: required
dist: trusty


branches:
  only:
    - /^\d+.*$/

env:

install:
  - sudo apt-get update && sudo apt-get install -y p7zip-full

jobs:
  include:
    - stage: departement
      script: bash makeDep.sh 001
    - script: bash makeDep.sh 002
    - script: bash makeDep.sh 003
    - script: bash makeDep.sh 004
    - script: bash makeDep.sh 005
    - script: bash makeDep.sh 006
    - script: bash makeDep.sh 007
    - script: bash makeDep.sh 008
    - script: bash makeDep.sh 009
    - script: bash makeDep.sh 010
    - script: bash makeDep.sh 011
    - script: bash makeDep.sh 012
    - script: bash makeDep.sh 013
    - script: bash makeDep.sh 014
    - script: bash makeDep.sh 015
    - script: bash makeDep.sh 016
    - script: bash makeDep.sh 017
    - script: bash makeDep.sh 018
    - script: bash makeDep.sh 019
    - script: bash makeDep.sh 021
    - script: bash makeDep.sh 022
    - script: bash makeDep.sh 023
    - script: bash makeDep.sh 024
    - script: bash makeDep.sh 025
    - script: bash makeDep.sh 026
    - script: bash makeDep.sh 027
    - script: bash makeDep.sh 028
    - script: bash makeDep.sh 029
    - script: bash makeDep.sh 02A
    - script: bash makeDep.sh 02B
    - script: bash makeDep.sh 030
    - script: bash makeDep.sh 031
    - script: bash makeDep.sh 032
    - script: bash makeDep.sh 033
    - script: bash makeDep.sh 034
    - script: bash makeDep.sh 035
    - script: bash makeDep.sh 036
    - script: bash makeDep.sh 037
    - script: bash makeDep.sh 038
    - script: bash makeDep.sh 039
    - script: bash makeDep.sh 040
    - script: bash makeDep.sh 041
    - script: bash makeDep.sh 042
    - script: bash makeDep.sh 043
    - script: bash makeDep.sh 044
    - script: bash makeDep.sh 045
    - script: bash makeDep.sh 046
    - script: bash makeDep.sh 047
    - script: bash makeDep.sh 048
    - script: bash makeDep.sh 049
    - script: bash makeDep.sh 050
    - script: bash makeDep.sh 051
    - script: bash makeDep.sh 052
    - script: bash makeDep.sh 053
    - script: bash makeDep.sh 054
    - script: bash makeDep.sh 055
    - script: bash makeDep.sh 056
    - script: bash makeDep.sh 057
    - script: bash makeDep.sh 058
    - script: bash makeDep.sh 059
    - script: bash makeDep.sh 060
    - script: bash makeDep.sh 061
    - script: bash makeDep.sh 062
    - script: bash makeDep.sh 063
    - script: bash makeDep.sh 064
    - script: bash makeDep.sh 065
    - script: bash makeDep.sh 066
    - script: bash makeDep.sh 067
    - script: bash makeDep.sh 068
    - script: bash makeDep.sh 069
    - script: bash makeDep.sh 070
    - script: bash makeDep.sh 071
    - script: bash makeDep.sh 072
    - script: bash makeDep.sh 073
    - script: bash makeDep.sh 074
    - script: bash makeDep.sh 075
    - script: bash makeDep.sh 076
    - script: bash makeDep.sh 077
    - script: bash makeDep.sh 078
    - script: bash makeDep.sh 079
    - script: bash makeDep.sh 080
    - script: bash makeDep.sh 081
    - script: bash makeDep.sh 082
    - script: bash makeDep.sh 083
    - script: bash makeDep.sh 084
    - script: bash makeDep.sh 085
    - script: bash makeDep.sh 086
    - script: bash makeDep.sh 087
    - script: bash makeDep.sh 088
    - script: bash makeDep.sh 089
    - script: bash makeDep.sh 090
    - script: bash makeDep.sh 091
    - script: bash makeDep.sh 092
    - script: bash makeDep.sh 093
    - script: bash makeDep.sh 094
    - script: bash makeDep.sh 095
    - script: bash makeDep.sh 971
    - script: bash makeDep.sh 972
    - script: bash makeDep.sh 973
    - script: bash makeDep.sh 974
    - script: bash makeDep.sh 975
    - script: bash makeDep.sh 976
    - script: bash makeDep.sh 977
    - script: bash makeDep.sh 978
    - script: bash makeDep.sh 986


deploy:
  provider: releases
  api_key: $GH_TOKEN
  file_glob: true
  file: D*.tar.gz
  skip_cleanup: true
  on:
    repo: tcoupin/rok4_gen_bdortho
    tags: true