language: bash

sudo: required
dist: trusty

cache:
  directories:
    - workspace

branches:
  only:
    - /^\d+.*$/


install:
  - sudo apt-get update && sudo apt-get install -y p7zip-full


jobs:
  include:
    - &jobsd
      stage: departments initialization
      script:
        - bash scripts/.travis/prepare_size.sh 75,93,94,92
        - bash scripts/.travis/split.sh workspace/sizes 4 $ITEM scripts/departement/download.sh scripts/departement/prepare.sh
      env:
        - ITEM=1
    - <<: *jobsd
      env: 
        - ITEM=2
    - <<: *jobsd
      env: 
        - ITEM=3
    - <<: *jobsd
      env: 
        - ITEM=4
    - &jobsg
      stage: departments generate
      script: bash scripts/.travis/split.sh workspace/sizes 4 $ITEM scripts/departement/generate.sh scripts/departement/docker-image.sh
      env:
        - ITEM=1
      deploy:
        provider: releases
        api_key: $GH_TOKEN
        file_glob: true
        file: workspace/**/*.tar.gz
        skip_cleanup: true
        overwrite: true
        on:
          repo: tcoupin/rok4_gen_bdortho
          tags: true
    - <<: *jobsg
      env: 
        - ITEM=2
    - <<: *jobsg
      env: 
        - ITEM=3
    - <<: *jobsg
      env: 
        - ITEM=4
    - stage: world download
      script: bash scripts/world/download.sh 75,93,94,92
    - stage: world prepare
      script: 
        - chmod -R 777 workspace
        - bash scripts/world/prepare.sh 75,93,94,92
    - stage: world generate
      script: 
        - chmod -R 777 workspace
        - bash scripts/world/generate.sh
      deploy:
        provider: releases
        api_key: $GH_TOKEN
        file_glob: true
        file: workspace/**/*.tar.gz
        skip_cleanup: true
        overwrite: true
        on:
          repo: tcoupin/rok4_gen_bdortho
          tags: true
    - stage: world docker
      script: 
        - chmod -R 777 workspace
        - bash scripts/world/docker-image.sh 

